#!/usr/bin/env bash
#if has an eq equality used for comparison which w
#ill evaluates at 9th value.
x=1
while [ $x -le 10 ]
do
    echo "Best School"
    if [ $x -eq 9 ]
    then
	echo "Hi"
   fi
   ((x++))
done
