#!/usr/bin/env bash
#bash script to explore the uce of case statements
x=1
while [ $x -le 20 ]
do
	echo "$x"
	case $x in
	     4)
		echo "bad luck from china"
		;;
	     9)
		echo "bad luck from japan"
		;;
	     17)
		echo "bad luck from italy"
		;;
	esac
	((x++))
done
