#!/usr/bin/env bash
#creating a bash script using nested if statements
file="school"
if [ -e $file ]
then
	echo "$file file exist"

	if [ -s $file ]
	then
		echo "$file fileis not empty"
	else
		echo "$file file is empty"
	fi

	if [ -f $file ]
	then
		echo "$file is a regular file"

	fi
else
	echo "$file file does not exist"
	fi
